[build]
  command = "bash build.sh"
  publish = "app/build/web"
  functions = "backend/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/imprimir-qr"
  to = "/.netlify/functions/api/imprimir-qr"
  status = 200

[[redirects]]
  from = "/descargar-app"
  to = "/public/app-release.apk"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
